In [3]:
# Broadcasting: you will need it while you ar dealing with data analysis
import numpy as np


In [8]:
X = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]])
X.shape
X.shape[0]

4

In [16]:
X = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]])
w = np.array([10,20,30])

# Task: add w array four times in X matrices(each row)

Y = X

for i in range(X.shape[0]):
    Y[i,:] = X[i,:] + w

print(Y), print('')
print(X)

[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]

[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]


In [17]:
# Y = X  it creates a memory buffer with same object.
# that means, if you change Y, you change X
# to solve this problem you need to import another library copy

import copy
X = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]])

X = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]])
w = np.array([10,20,30])

# Task: add w array four times in X matrices(each row)

Y = copy.deepcopy(X)

for i in range(X.shape[0]):
    Y[i,:] = X[i,:] + w

print(Y), print('')
print(X)


[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [18]:
# instead doing like this, broadcasting is better solution.

Y = X + w

print(Y), print('')
print(X)

# in the point of linear algebra this operation is wrong.
# but python checks the dimensions and does the operation multiple times
# python does this operation elementwise


[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [19]:
w = [-1,0,1] # this is a list. Broadcasting also works for lists
X*w


array([[-1,  0,  3],
       [-2,  0,  4],
       [-3,  0,  5],
       [-4,  0,  6]])

In [27]:
w = np.array([-1,0,1,0],ndmin=2).T #lets multiply columns instead of rows
# ndmin defines the minimum number of dimension
X*w


array([[-1, -2, -3],
       [ 0,  0,  0],
       [ 3,  4,  5],
       [ 0,  0,  0]])

In [29]:
# Exercise:
# 1) create a list of integers from 0 to 8 (v)
# 2) reshape to a 3x3 matrix(M)
# 3) repeat that matrix to 9x3 (C)
# 4) broadcast-multiply(columnwise) with individual vector(v) (B)


In [37]:
v = np.arange(0,9)
print(v), print('')

M = np.reshape(v,(3,3))
print(M), print('')

C = np.tile(M,(3,1))
print(C), print('')

B = C*np.reshape(v,(len(v),1))
print(B), print('')

w = np.reshape(v,(len(v),1))
print(w.shape)
print(v.shape)

[0 1 2 3 4 5 6 7 8]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]
 [ 0  3  6]
 [12 16 20]
 [30 35 40]
 [ 0  6 12]
 [21 28 35]
 [48 56 64]]

(9, 1)
(9,)
