# 🚀 AE 444 - Computer Programming
## Python Basics — Broadcasting in NumPy

In this notebook, we will explore **broadcasting**, a powerful feature of NumPy that allows arithmetic operations between arrays of different shapes. Broadcasting simplifies code and improves performance by avoiding explicit loops.

## Learning Goals
By the end of this notebook, students will be able to:
- Understand the concept of broadcasting in NumPy.
- Perform element-wise operations between arrays of different shapes.
- Use `copy.deepcopy()` to create independent copies of arrays.
- Reshape arrays using `np.reshape()` and `ndmin`.
- Apply broadcasting to solve matrix operations efficiently.


## 1. The Problem: Adding a Vector to a Matrix
Suppose you have a matrix `X` and a vector `w`, and you want to add `w` to each row of `X`.

**Example:**

In [16]:
import numpy as np
import copy

X = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [3, 4, 5],
    [4, 5, 6]
])
w = np.array([10, 20, 30])

print("Original X:\n", X)
print("Vector w:", w)


[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]

[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]


## 2. The Loop Approach (Inefficient)
You could iterate through each row and add the vector. However, be careful with variable assignment! `Y = X` creates a reference, not a copy. Modifying `Y` will also modify `X`.

To create a true copy, use `copy.deepcopy()`.


In [18]:
# Create a deep copy to avoid modifying X
Y = copy.deepcopy(X)

for i in range(X.shape[0]):
    Y[i, :] = X[i, :] + w

print("\nResult Y (Loop):\n", Y)
print("Original X (Unchanged):\n", X)


[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


## 3. The Broadcasting Approach (Efficient)
NumPy allows you to perform this operation directly without a loop. It automatically "broadcasts" the smaller array across the larger one.


In [27]:
# Broadcasting addition
Y_broadcast = X + w

print("\nResult Y (Broadcasting):\n", Y_broadcast)

# Note: In linear algebra, adding a vector to a matrix is not defined.
# But NumPy interprets this as adding the vector to each row.


array([[-1, -2, -3],
       [ 0,  0,  0],
       [ 3,  4,  5],
       [ 0,  0,  0]])

## 4. Broadcasting with Different Dimensions
Broadcasting works by aligning dimensions. If you want to operate on columns instead of rows, you need to reshape the vector.


In [37]:
# Create a column vector (4x1)
w_col = np.array([-1, 0, 1, 0], ndmin=2).T

print("\nColumn vector w_col:\n", w_col)

# Multiply X by w_col (element-wise, broadcasting across columns)
result = X * w_col
print("\nResult (Column Broadcasting):\n", result)


[0 1 2 3 4 5 6 7 8]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]
 [ 0  3  6]
 [12 16 20]
 [30 35 40]
 [ 0  6 12]
 [21 28 35]
 [48 56 64]]

(9, 1)
(9,)


## 5. Practice Task: Matrix Manipulation
**Exercise:**
1.  Create a list of integers from 0 to 8 (`v`).
2.  Reshape it into a 3x3 matrix (`M`).
3.  Repeat that matrix to make it 9x3 (`C`).
4.  Broadcast-multiply (column-wise) with the original vector `v` (reshaped to 9x1) to get `B`.


In [ ]:
# 1. Create vector v
v = np.arange(0, 9)
print("Vector v:", v)

# 2. Reshape to 3x3 matrix M
M = np.reshape(v, (3, 3))
print("\nMatrix M:\n", M)

# 3. Repeat matrix to 9x3 C
# np.tile repeats the array: 3 times vertically, 1 time horizontally
C = np.tile(M, (3, 1))
print("\nMatrix C (9x3):\n", C)

# 4. Broadcast-multiply with v (reshaped to 9x1)
# We need v to be a column vector (9, 1) to broadcast across columns of C
v_col = np.reshape(v, (len(v), 1))
print("\nReshaped v (9x1):\n", v_col)

B = C * v_col
print("\nResult B:\n", B)


## 6. Wrap-Up
You have learned how to use broadcasting to perform efficient array operations in NumPy. This technique is fundamental for writing concise and fast numerical code in Python.
